In [1]:
!pip install sdv

Requirement already satisfied: sdv in /usr/local/lib/python3.12/dist-packages (1.34.1)
Requirement already satisfied: boto3<2.0.0,>=1.28 in /usr/local/lib/python3.12/dist-packages (from sdv) (1.42.54)
Requirement already satisfied: botocore<2.0.0,>=1.31 in /usr/local/lib/python3.12/dist-packages (from sdv) (1.42.54)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (3.1.2)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.21)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.0.2)
Requirement already satisfied: pandas<3,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (2.2.2)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.67.3)
Requirement already satisfied: copulas>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.14.1)
Requirement already satisfied: ctgan>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.12.1)
Requirement already satisfied: deepecho>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.8.1)
Requirement already satisfied: rdt>=1.18.2 in /usr/local/lib/python3.12/dist-packages (from sdv) (1.20.0)
Requirement already satisfied: sdmetrics>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (0.27.1)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.12/dist-packages (from sdv) (4.9.2)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from sdv) (6.0.3)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3<2.0.0,>=1.28->sdv) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from boto3<2.0.0,>=1.28->sdv) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.5.0)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from copulas>=0.12.1->sdv) (1.16.3)
Requirement already satisfied: torch>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from ctgan>=0.11.1->sdv) (2.10.0+cu128)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.1.1->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=2.1.1->sdv) (2025.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.18.2->sdv) (1.6.1)
Requirement already satisfied: Faker!=37.11.0,>=17 in /usr/local/lib/python3.12/dist-packages (from rdt>=1.18.2->sdv) (40.4.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->rdt>=1.18.2->sdv) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.24.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.3.0->ctgan>=0.11.1->sdv) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.3.0->ctgan>=0.11.1->sdv) (1.3.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.3.0->ctgan>=0.11.1->sdv) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.3.0->ctgan>=0.11.1->sdv) (3.0.3)

In [2]:
import pandas as pd
import numpy as np
import os
import gc

from sdv.single_table import CTGANSynthesizer
from sdv.metadata import SingleTableMetadata

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
BASE_PATH = "/content/drive/MyDrive/MajorProject"

TRAIN_PATH = f"{BASE_PATH}/CIC_IoT_2023/Full_Dataset/train_working.csv"
GAN_OUT_PATH = f"{BASE_PATH}/IDS_GAN_Outputs"

LABEL_COL = "label"
RANDOM_SEED = 42

In [5]:
print("Loading training data")
train_df = pd.read_csv(TRAIN_PATH, low_memory=False)

print("Initial shape", train_df.shape)

Loading training data
Initial shape (900000, 47)

In [6]:
train_df = train_df.dropna(subset=[LABEL_COL])
print("After label cleaning:", train_df.shape)

After label cleaning: (900000, 47)

In [7]:
GAN_TARGET_CLASSES = [
    "Recon-PingSweep",
    "Uploading_Attack",
    "SqlInjection",
    "BrowserHijacking",
    "Backdoor_Malware",
    "XSS"
]

gan_train_df = train_df[train_df[LABEL_COL].isin(GAN_TARGET_CLASSES)]

print("GAN training data shape:", gan_train_df.shape)
gan_train_df[LABEL_COL].value_counts()

GAN training data shape: (12851, 47)

label
BrowserHijacking    3522
SqlInjection        3104
XSS                 2257
Backdoor_Malware    1892
Recon-PingSweep     1319
Uploading_Attack     757
Name: count, dtype: int64

In [8]:
# Create SDV metadata
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(gan_train_df)

metadata

{
    "columns": {
        "flow_duration": {
            "sdtype": "numerical"
        },
        "Header_Length": {
            "sdtype": "numerical"
        },
        "Protocol Type": {
            "sdtype": "numerical"
        },
        "Duration": {
            "sdtype": "numerical"
        },
        "Rate": {
            "sdtype": "numerical"
        },
        "Srate": {
            "sdtype": "numerical"
        },
        "Drate": {
            "sdtype": "categorical"
        },
        "fin_flag_number": {
            "sdtype": "categorical"
        },
        "syn_flag_number": {
            "sdtype": "categorical"
        },
        "rst_flag_number": {
            "sdtype": "categorical"
        },
        "psh_flag_number": {
            "sdtype": "categorical"
        },
        "ack_flag_number": {
            "sdtype": "categorical"
        },
        "ece_flag_number": {
            "sdtype": "categorical"
        },
        "cwr_flag_number": {
            "sdtype": "categorical"
        },
        "ack_count": {
            "sdtype": "numerical"
        },
        "syn_count": {
            "sdtype": "numerical"
        },
        "fin_count": {
            "sdtype": "numerical"
        },
        "urg_count": {
            "sdtype": "numerical"
        },
        "rst_count": {
            "sdtype": "numerical"
        },
        "HTTP": {
            "sdtype": "categorical"
        },
        "HTTPS": {
            "sdtype": "categorical"
        },
        "DNS": {
            "sdtype": "categorical"
        },
        "Telnet": {
            "sdtype": "categorical"
        },
        "SMTP": {
            "sdtype": "categorical"
        },
        "SSH": {
            "sdtype": "categorical"
        },
        "IRC": {
            "sdtype": "categorical"
        },
        "TCP": {
            "sdtype": "categorical"
        },
        "UDP": {
            "sdtype": "categorical"
        },
        "DHCP": {
            "sdtype": "categorical"
        },
        "ARP": {
            "sdtype": "categorical"
        },
        "ICMP": {
            "sdtype": "categorical"
        },
        "IPv": {
            "sdtype": "categorical"
        },
        "LLC": {
            "sdtype": "categorical"
        },
        "Tot sum": {
            "sdtype": "numerical"
        },
        "Min": {
            "sdtype": "numerical"
        },
        "Max": {
            "sdtype": "numerical"
        },
        "AVG": {
            "sdtype": "numerical"
        },
        "Std": {
            "sdtype": "numerical"
        },
        "Tot size": {
            "sdtype": "numerical"
        },
        "IAT": {
            "sdtype": "numerical"
        },
        "Number": {
            "sdtype": "numerical"
        },
        "Magnitue": {
            "sdtype": "numerical"
        },
        "Radius": {
            "sdtype": "numerical"
        },
        "Covariance": {
            "sdtype": "numerical"
        },
        "Variance": {
            "sdtype": "numerical"
        },
        "Weight": {
            "sdtype": "numerical"
        },
        "label": {
            "sdtype": "categorical"
        }
    },
    "METADATA_SPEC_VERSION": "SINGLE_TABLE_V1"
}

In [9]:
ctgan = CTGANSynthesizer(
    metadata=metadata,
    epochs=300,
    batch_size=2048,
    generator_lr=2e-4,
    discriminator_lr=2e-4,
    verbose=True,
    cuda=True,
    pac=1
)

/usr/local/lib/python3.12/dist-packages/sdv/single_table/base.py:168: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
/usr/local/lib/python3.12/dist-packages/sdv/single_table/base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/ctgan/synthesizers/_utils.py:16: FutureWarning: `cuda` parameter is deprecated and will be removed in a future release. Please use `enable_gpu` instead.
  warnings.warn(

In [10]:
print("Training CTGAN on minority classes")
ctgan.fit(gan_train_df)

Training CTGAN on minority classes

Gen. (-00.16) | Discrim. (-00.13): 100%|██████████| 300/300 [02:32<00:00,  1.97it/s]

In [11]:
real_counts = gan_train_df[LABEL_COL].value_counts()
real_counts

label
BrowserHijacking    3522
SqlInjection        3104
XSS                 2257
Backdoor_Malware    1892
Recon-PingSweep     1319
Uploading_Attack     757
Name: count, dtype: int64

In [12]:
# generate upto 1x real samples per class
synthetic_counts = real_counts.to_dict()
synthetic_counts

{'BrowserHijacking': 3522,
 'SqlInjection': 3104,
 'XSS': 2257,
 'Backdoor_Malware': 1892,
 'Recon-PingSweep': 1319,
 'Uploading_Attack': 757}

## Generate synthetic data per class

In [13]:
synthetic_rows = []

for cls, n_samples in synthetic_counts.items():
    print(f"Generating {n_samples} samples for class {cls}")
    samples = ctgan.sample(num_rows=n_samples)
    samples[LABEL_COL] = cls

    synthetic_rows.append(samples)

synthetic_df = pd.concat(synthetic_rows, ignore_index=True)
print("Synthetic data shape:", synthetic_df.shape)

Generating 3522 samples for class BrowserHijacking
Generating 3104 samples for class SqlInjection
Generating 2257 samples for class XSS
Generating 1892 samples for class Backdoor_Malware
Generating 1319 samples for class Recon-PingSweep
Generating 757 samples for class Uploading_Attack
Synthetic data shape: (12851, 47)

## Save synthetic dataset

In [14]:
SYNTHETIC_PATH = f"{BASE_PATH}/CIC_IoT_2023/Full_Dataset/synthetic_minority_data.csv"
synthetic_df.to_csv(SYNTHETIC_PATH, index=False)

print("Synthetic data saved to:", SYNTHETIC_PATH)

Synthetic data saved to: /content/drive/MyDrive/MajorProject/CIC_IoT_2023/Full_Dataset/synthetic_minority_data.csv

In [15]:
augmented_train_df = pd.concat(
    [train_df, synthetic_df],
    ignore_index=True
)
print("Augmented data shape:", augmented_train_df.shape)

Augmented data shape: (912851, 47)

In [16]:
AUGMENTED_PATH = f"{BASE_PATH}/CIC_IoT_2023/Full_Dataset/augmented_train_data.csv"
augmented_train_df.to_csv(AUGMENTED_PATH, index=False)

print("Augmented data saved to: ", AUGMENTED_PATH)

Augmented data saved to:  /content/drive/MyDrive/MajorProject/CIC_IoT_2023/Full_Dataset/augmented_train_data.csv

In [17]:
del train_df, gan_train_df, synthetic_df, augmented_train_df
gc.collect()

0